### ISSUE TITLE
Heckman Swanson Biscuit Burn

### ISSUE THREAD

**Issue by kristenfrederick** [ISCN/SOCDRaHR2#20]
I just uploaded the HeckmanSwansonBiscuitBurn.rmd in commit 73284e1 can you check it out when you get the chance @ktoddbrown

**Comment by annabel39** [comment]
- [x] Evaluate dataset
- [x] merge study data
- [x] clean up profile data
- [x] clean up layer data
- [x] make graphics
- [ ] Confirm control and burn 7 having same coords
- [x] Write up summary report narrative
- [x] Good commenting
- [ ] External review by someone else!

**Comment by ritahippe** [comment]
Reformatted so that maps and tables were in individual chunks, as well as finishing comments. Added narrative at line 47, and removed empty variables "all_layer", "all_study" and two more of the same nature in 0c6c2af

**Comment by ktoddbrown** [comment]
Fixes and review:

- [x] Remove names from the chunk (example: https://github.com/ISCN/SOCDRaHR2/blob/c1ae01bbd91f32cf95f3c995e8288b4f09d2b785/data_reports/102_HeckmanSwanstonBiscuitBurn.Rmd#L3 should be triple tick `{r}`
- [x] Use a negative select on the profile construction instead of the positive select (use   `select(-dataset_name_soc, -starts_with('soc')) %>%`  instead of https://github.com/ISCN/SOCDRaHR2/blob/c1ae01bbd91f32cf95f3c995e8288b4f09d2b785/data_reports/102_HeckmanSwanstonBiscuitBurn.Rmd#L25) comment on why you are dropping these columns (ie `#removing ISCN flags that say nothing was done for the SOC fill`)
- [x] Similar with dataset_layer for select and commenting
- [x] break out the figures into their own chunks
- [x] put spaces before and after the - in the TODO list at the end to get them to render nicely

**Comment by ritahippe** [comment]
Added citations to all appropriate files in 0c6c2af

**Comment by ritahippe** [comment]
Slightly modified to match new template. Now just awaiting external review. @ktoddbrown  1fa99ea

**Comment by ktoddbrown** [comment]
Let's add a "how" the ISCN3 fill was removed from the dataset. Most of the time it will be either the entire columns associated with SOC were removed or ISCN flagged values were replaced with NA in an if_else function, values could have been filled up-down the group, and the duplicate rows were removed. @ritahippe @kristenfrederick @annabel39
